apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      containers:
      - name: node-exporter
        image: prom/node-exporter
        volumeMounts:
          - name: rootfs
            mountPath: /rootfs
            readOnly: false
          - name: sys
            mountPath: /host/sys
            readOnly: false
          - name: proc
            mountPath: /host/proc
            readOnly: false
        ports:
          - name: node-exp-port
            containerPort: 9100
            protocol: TCP
        args:
          - collector.procfs /host/proc
          - collector.sysfs /host/sys
          - collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
