apiVersion: v1
kind: Service
metadata:
  labels:
    name: prom-svc
  name: prom-svc
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - name: grafana-port
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: prom-port
      protocol: TCP
      port: 81
      targetPort: 9090
