version: '3.1'

services:
  api-bench:
    image: "${ABIMAGE}"
    deploy:
      replicas: 4
      restart_policy:
        condition: never
    network_mode: "host"
    command: ["--action", "${ABACTION}"]
