FROM buildpack-deps:xenial
RUN apt-get update && apt-get install -y --no-install-recommends python3-dev python3-pip python3-setuptools python3-wheel
RUN pip3 install -U thrift
COPY ./gen-py /gen-py
COPY client.py /
ENTRYPOINT ["python3", "/client.py"]
