FROM buildpack-deps:xenial
RUN apt-get update && apt-get install -y --no-install-recommends python3-dev python3-pip python3-setuptools python3-wheel
RUN pip3 install thrift
COPY ./gen-py /gen-py
COPY client.py /
ENTRYPOINT ["/usr/bin/python3", "/client.py"]
