FROM buildpack-deps:xenial
# Either "3" or empty
ARG PYTHON_VERSION=3
RUN apt-get update && apt-get install -y --no-install-recommends python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-pip python${PYTHON_VERSION}-setuptools python${PYTHON_VERSION}-wheel
RUN pip${PYTHON_VERSION} install -U thrift
COPY ./gen-py /gen-py
COPY server.py /
ENV PYTHON python${PYTHON_VERSION}
ENTRYPOINT ${PYTHON} /server.py
