apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ossprojsvr
  labels:
    bu: eng
spec:
  replicas: 10
  template:
    metadata:
      labels:
        appname: ossproj
        targetenv: demo
    spec:
      containers:
      - name: ossprojsvrc
        image: nsuke/tpydemosvr:v1
        ports:
        - containerPort: 9090
